ExamDjangoBasic/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('recipes.urls'))
]

recipes/urls.py
from django.urls import path

import recipes.views as views

urlpatterns = [
    path('', views.home_page, name='home page'),
    path('create/', views.create, name='create'),
    path('edit/<int:pk>', views.edit, name='edit'),
    path('delete/<int:pk>', views.delete, name='delete'),
    path('details/<int:pk>', views.details, name='details'),

]

recipes/models.py
from django.db import models


# Create your models here.
class Recipes(models.Model):
    title = models.CharField(max_length=30)
    images_url = models.URLField()
    description = models.TextField()
    ingredients = models.CharField(max_length=250)
    time = models.IntegerField()

recipes/forms.py
from django import forms

from recipes.models import Recipes


class FormRecipes(forms.ModelForm):
    class Meta:
        model = Recipes
        fields = '__all__'

recipes/views.py
from django.shortcuts import render, redirect

# Create your views here.
from recipes.forms import FormRecipes
from recipes.models import Recipes


def home_page(req):
    recipes = Recipes.objects.all()
    return render(req, 'index.html', {'recipes': recipes})


def create(req):
    if req.method == 'GET':
        form = FormRecipes()
        return render(req, 'create.html', {'form': form})
    else:
        form = FormRecipes(req.POST)
        if form.is_valid():
            form.save()
            return redirect('home page')
        return render(req, 'create.html', {'form': form})


def edit(req, pk):
    recipes = Recipes.objects.get(pk=pk)
    if req.method == 'GET':
        form = FormRecipes(instance=recipes)
        return render(req, 'edit.html', {'form': form})
    else:
        form = FormRecipes(req.POST, instance=recipes)
        if form.is_valid():
            form.save()
            return redirect('home page')
        return render(req, 'edit.html', {'form': form})


def delete(req, pk):
    recipes = Recipes.objects.get(pk=pk)
    if req.method == 'GET':
        form = FormRecipes(instance=recipes)
        form.fields['title'].widget.attrs['readonly'] = True
        form.fields['images_url'].widget.attrs['readonly'] = True
        form.fields['description'].widget.attrs['readonly'] = True
        form.fields['ingredients'].widget.attrs['readonly'] = True
        form.fields['time'].widget.attrs['readonly'] = True
        return render(req, 'delete.html', {'form': form})
    else:
        recipes.delete()
        return redirect('home page')


def details(req, pk):
    recipes = Recipes.objects.get(pk=pk)
    ingredients = recipes.ingredients.split(", ")
    context = {
        'recipes': recipes,
        'ingredients': ingredients,
        'pk': pk,

    }
    return render(req, 'details.html', context)

templates/common/navbar.html
{% load static %}
<nav>
    <ul>
        <img src="{% static 'images/chef.png' %}" alt="chef">
        <li class="title"><a href="/">Recipes</a></li>
        <li><a href="{% url 'create' %}">Add Recipe</a></li>
    </ul>
</nav>

templates/common/site.html
{% load static %}
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <title>{% block title %}Recipes{% endblock %}</title>
</head>

<body>
{% include 'common/navbar.html' %}

{% block site_content %}

{% endblock %}
</body>

</html>

templates/create.html
{% extends 'common/site.html' %}

{% block title %} Create Recipes {% endblock %}
{% block site_content %}
    <div class="container">

        <h1>Create Recipe</h1>
        <div class="items-container">
            <div class="item">
                <form method="POST">
                    {% csrf_token %}
                    {{ form.errors }}
                    <label for="title">Title</label>
                    {#            <input type="text" name="title" maxlength="30" required="" id="id_title">#}
                    {{ form.title }}
                    <label for="imageURL">Image URL</label>
                    {#            <input type="url" name="image_url" maxlength="200" required="" id="id_image_url">#}
                    {{ form.images_url }}
                    <label for="description">Description</label>
                    {#            <textarea name="description" cols="40" rows="10" required="" id="id_description"></textarea>#}
                    {{ form.description }}
                    <label for="ingredients">Ingredients</label>
                    {#            <input type="text" name="ingredients" maxlength="250" required="" id="id_ingredients">#}
                    {{ form.ingredients }}
                    <label for="time">Time (Minutes)</label>
                    {#            <input type="number" name="time" required="" id="id_time">#}
                    {{ form.time }}
                    <input type="submit" value="Create">
                </form>
            </div>
        </div>

    </div>

{% endblock %}

templates/delete.html
{% extends 'common/site.html' %}
{% load static %}

{% block title %} Delete Recipes {% endblock %}


{% block site_content %}
    <div class="container">

        <h1>Delete Recipe</h1>
        <div class="items-container">
            <div class="item">
                <form method="POST">
                    {% csrf_token %}
                    <label for="title">Title</label>
                    {#            <input type="text" name="title" value="Homemade Chicken Soup" maxlength="30" disabled="" required="" id="id_title">#}
                    {{ form.title }}
                    <label for="imageURL">Image URL</label>
                    {#            <input type="url" name="image_url" value="https://i.ytimg.com/vi/o91gT73mQhg/maxresdefault.jpg" maxlength="200" disabled="" required="" id="id_image_url">#}
                    {{ form.images_url }}
                    <label for="description">Description</label>
                    {#            <textarea name="description" cols="40" rows="10" disabled="" required="" id="id_description">Put the chicken, carrots, celery and onion in a large soup pot and cover with cold water. Heat and simmer, uncovered, until the chicken meat falls off of the bones (skim off foam every so often).#}
                    {#Take everything out of the pot. Strain the broth. Pick the meat off of the bones and chop the carrots, celery and onion. Season the broth with salt, pepper and chicken bouillon to taste, if desired. Return the chicken, carrots, celery and onion to the pot, stir together, and serve.</textarea>#}
                    {{ form.description }}
                    <label for="ingredients">Ingredients</label>
                    {#                    <input type="text" name="ingredients"#}
                    {#                           value="1 (3 pound) whole chicken, 4 medium (blank)s carrots halved, 4 stalks celery halved, 1 large onion halved, water to cover, salt and pepper to taste, 1 teaspoon chicken bouillon granules"#}
                    {#                           maxlength="250" disabled="" required="" id="id_ingredients">#}
                    {{ form.ingredients }}
                    <label for="time">Time (Minutes)</label>
                    {#                    <input type="number" name="time" value="30" disabled="" required="" id="id_time">#}
                    {{ form.time }}
                    <input type="submit" class="button delete" value="Delete">
                </form>
            </div>
        </div>

    </div>

{% endblock %}

templates/details.html
{% extends 'common/site.html' %}
{% load static %}
{% block title %} Detail Recipes{% endblock %}

<body>

{% block site_content %}
    <div class="container">

        <h1>Recipe Details</h1>
        <div class="items-container">
            <div class="item">
                <h2>{{ recipes.title }}</h2>
                <img class="detail-img" src="{{ recipes.images_url }}" alt="recipe-image">
                <div class="time">
                    <img src="{% static 'images/clock.png' %}">
                    <p>{{ recipes.time }}</p>
                </div>
                <h3>Ingredients</h3>
                <ul>
                    {% for ing in ingredients %}
                        <li>{{ ing }}</li>
                    {% endfor %}

                </ul>
                <h3>How to prepare?</h3>
                <div class="recipe-info-full">
                   {{ recipes.description }}
                </div>
                <div class="buttons-container">
                    <a class="button edit" href="{% url 'edit' pk %}">Edit</a>
                    <a class="button delete" href="{% url 'delete' pk %}">Delete</a>
                </div>
            </div>
        </div>

    </div>


{% endblock %}

templates/edit.html
{% extends 'common/site.html' %}

{% block title %} Edit Recipes {% endblock %}
{% block site_content %}
    <div class="container">

        <h1>Edit Recipe</h1>
        <div class="items-container">
            <div class="item">
                <form method="POST">
                    {% csrf_token %}
                    {{ form.errors }}
                    <label for="title">Title</label>
                    {#            <input type="text" name="title" value="Homemade Chicken Soup" maxlength="30" required="" id="id_title">#}
                    {{ form.title }}
                    <label for="imageURL">Image URL</label>
                    {#            <input type="url" name="image_url" value="https://i.ytimg.com/vi/o91gT73mQhg/maxresdefault.jpg" maxlength="200"  required="" id="id_image_url">#}
                    {{ form.images_url }}
                    <label for="description">Description</label>
                    {#            <textarea name="description" cols="40" rows="10"  required="" id="id_description">Put the chicken, carrots, celery and onion in a large soup pot and cover with cold water. Heat and simmer, uncovered, until the chicken meat falls off of the bones (skim off foam every so often).#}
                    {#Take everything out of the pot. Strain the broth. Pick the meat off of the bones and chop the carrots, celery and onion. Season the broth with salt, pepper and chicken bouillon to taste, if desired. Return the chicken, carrots, celery and onion to the pot, stir together, and serve.</textarea>#}
                    {{ form.description }}
                    <label for="ingredients">Ingredients</label>
                    {{ form.ingredients }}
                    {#                    <input type="text" name="ingredients"#}
                    {#                           value="1 (3 pound) whole chicken, 4 medium (blank)s carrots halved, 4 stalks celery halved, 1 large onion halved, water to cover, salt and pepper to taste, 1 teaspoon chicken bouillon granules"#}
                    {#                           maxlength="250" required="" id="id_ingredients">#}
                    <label for="time">Time (Minutes)</label>
                    {{ form.time }}
                    {#                    <input type="number" name="time" value="30" required="" id="id_time">#}
                    <input type="submit" class="button edit" value="Edit">
                </form>
            </div>
        </div>

    </div>


{% endblock %}

templates/index.html
{% extends 'common/site.html' %}

{% block title %} Home {% endblock %}

{% block site_content %}
    <div class="container">

        <h1>My Recipes</h1>
        {% if not recipes %}
            <h2>There are no recipes.</h2>
        {% endif %}

        <div class="items-container">
            {% for rep in recipes %}
                <div class="item">
                    <h2>{{ rep.title }}</h2>
                    <img class="detail-img" src="{{ rep.images_url }}" alt="recipe-image">
                    <div class="recipe-info">
                        {{ rep.description }}
                    </div>
                    <div class="buttons-container">
                        <a class="button detail" href="{% url 'details' rep.id %}">Details</a>
                        <a class="button edit" href="{% url 'edit' rep.id %}">Edit</a>
                        <a class="button delete" href="{% url 'delete' rep.id %}">Delete</a>
                    </div>
                </div>
            {% endfor %}
            {#            <div class="item">#}
            {#                <h2>Cardamom Maple Salmon (Edit)</h2>#}
            {#                <img class="detail-img" src="https://imagesvc.meredithcorp.io/v3/mm/image?url=https%3A%2F%2Fimages.media-allrecipes.com%2Fuserphotos%2F1122494.jpg&amp;w=596&amp;h=596&amp;c=sc&amp;poi=face&amp;q=85" alt="recipe-image">#}
            {#                <div class="recipe-info">#}
            {#                    Stir salt, paprika, cardamom, coriander, and black pepper together in a bowl. Add oil and maple syrup and stir until evenly combined. Preheat a non-stick frying pan over medium-high heat, about 350 degrees F (175 degrees C). Dredge salmon pieces through#}
            {#                    the maple syrup mixture until evenly coated on all sides. Cook salmon in the preheated pan until fish flakes easily with a fork, 5 to 7 minutes per side.#}
            {#                </div>#}
            {#                <div class="buttons-container">#}
            {#                    <a class="button detail" href="./details.html">Details</a>#}
            {#                    <a class="button edit" href="./edit.html">Edit</a>#}
            {#                    <a class="button delete" href="./delete.html">Delete</a>#}
            {#                </div>#}
            {#            </div>#}

        </div>

    </div>

{% endblock %}